# These are supported funding model platforms

community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom: https://en.wikipedia.org/wiki/Death_of_Mahsa_Amini
github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: # Replace with a single Ko-fi username
open_collective: # Replace with a single Open Collective username
patreon: # patron url
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
