[package]
categories = ["game-development", "game-engines", "games", "graphics", "multimedia", "wasm", "concurrency"]
description = "Wolf is a set of modules for realtime rendering, realtime streaming and game developing"
edition = "2021"
keywords = ["gamedev", "system", "gamedev", "render", "wasm", "web", "worker"]
license = "Apache-2.0"
name = "wolf-demo"
readme = "README.md"
repository = "https://github.com/WolfEngine/WolfEngine/"
version = "3.0.2"

[lib]
crate-type = ["cdylib"]
name = "wolf_demo"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.136",  features = ["derive"], default-features = false }
serde_closure = { version = "0.3.2", default-features = false }
wasm-bindgen = { version = "0.2.79", default-features = false }
wasm-mt = {version = "0.1.2", default-features = false }
wolfengine = { path = "../wolf", version = "3.0.1", features= ["system", "wasm"], default-features = false}

[dependencies.web-sys]
version = "0.3.56"
default-features = false
features = [
    'console',
]
