[package]
categories = ["game-development", "game-engines", "games", "graphics", "multimedia", "wasm", "concurrency"]
description = "Wolf is a set of modules for realtime rendering, realtime streaming and game developing"
edition = "2021"
keywords = ["gamedev", "system", "gamedev", "render", "wasm", "web", "worker"]
license = "Apache-2.0"
name = "wolf-demo"
readme = "README.md"
repository = "https://github.com/WolfEngine/WolfEngine/"
version = "3.0.0"

[lib]
crate-type = ["cdylib"]
name = "wolf_demo"
path = "src/lib.rs"

[dependencies]
#anyhow = "*"
#wolfengine = { path = "../wolf", version = "3.0.1" }
wasm-mt = "0.1.2"
serde = { version = "1.0.136", features = ["derive"] }
serde_closure = "0.3.2"
serde_traitobject = "0.2"
wasm-bindgen = { version = "0.2.79" }
wasm-bindgen-futures = "0.4.29"
console_error_panic_hook = { version = "0.1.7", optional = true }

[dependencies.web-sys]
version = "0.3.56"
default-features = false
features = [
    'console',
]
